apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-sensor-service-account
  namespace: home-security
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::125969980889:role/home-sensor-iam
